/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'poorak' at '10/6/14 9:52 PM' with Gradle 2.1
 *
 * @author poorak, @date 10/6/14 9:52 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
